server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: payment_routh # 路由的id，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径匹配的进行路由

        - id: payment_routh2 # 路由的id，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 # 过滤工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id,值为1024
          predicates:
            - Path=/payment/lb/** # 断言，路径匹配的进行路由
            - After=2020-08-16T09:15:56.741+08:00[Asia/Shanghai]
            #- Before=2020-08-20T09:15:56.741+08:00[Asia/Shanghai]
            #- Between=2020-08-16T09:15:56.741+08:00[Asia/Shanghai],2020-08-20T09:15:56.741+08:00[Asia/Shanghai]
            - Cookie=username,zzyy # 必须有cookie，且cookie中必须有username的属性，值为zzyy
            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性，并且值为正整数的正则表达式
            - Host=**.ochaly.com # 必须有host，且域名必须为ochaly.com
            - Method=GET # 请求方法必须为get
            - Query=username, \d+ # 要有参数名username并且值还是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
